// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl  = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!supabaseUrl  || !supabaseKey) {
  console.error("Missing Supabase environment variables. Please check your Vercel dashboard settings.");
  console.log("VITE_SUPABASE_URL:", supabaseUrl );
  console.log("VITE_SUPABASE_PUBLISHABLE_KEY:", supabaseKey);
}

export const supabase = createClient<Database>(supabaseUrl  || "", supabaseKey || "", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});